import type { ArchetypeDefinition, ArchetypeStorage } from '$lib/types/archetype';
import { DIRECTION_TAG, AXIS_TAG, MOTIVATION_TAG } from '$lib/types/tags';
import { WORLD_MARK } from '$lib/types/marks';
import { registerArchetype } from './storage';

/**
 * MVP 32 archetype definitions.
 * Array index matches ARCHETYPE constant values.
 * (e.g., ARCHETYPE.GUARDIAN = 0 → ARCHETYPE_DEFINITIONS[0])
 */
export const ARCHETYPE_DEFINITIONS: readonly ArchetypeDefinition[] = [
  // ── Protectors (0-3): Order + Others ──────────────────
  {
    name: 'Guardian',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.ORDER,
    secondaryAxis: AXIS_TAG.OTHERS,
    motivation: MOTIVATION_TAG.PROTECTION,
    worldMark: WORLD_MARK.BONE,
    weightActive: 70,
    weightPassive: 60,
    weightSocial: 40,
  },
  {
    name: 'Sentinel',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.ORDER,
    secondaryAxis: AXIS_TAG.STABLE,
    motivation: MOTIVATION_TAG.PROTECTION,
    worldMark: WORLD_MARK.EYE,
    weightActive: 60,
    weightPassive: 75,
    weightSocial: 30,
  },
  {
    name: 'Defender',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.ORDER,
    secondaryAxis: AXIS_TAG.STABLE,
    motivation: MOTIVATION_TAG.JUSTICE,
    worldMark: WORLD_MARK.BONE,
    weightActive: 75,
    weightPassive: 55,
    weightSocial: 35,
  },
  {
    name: 'Warden',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.ORDER,
    secondaryAxis: AXIS_TAG.CAUTIOUS,
    motivation: MOTIVATION_TAG.JUSTICE,
    worldMark: WORLD_MARK.EAR,
    weightActive: 65,
    weightPassive: 70,
    weightSocial: 35,
  },

  // ── Leaders (4-7): Social + Extra ─────────────────────
  {
    name: 'Commander',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.EXTRA,
    secondaryAxis: AXIS_TAG.ORDER,
    motivation: MOTIVATION_TAG.POWER,
    worldMark: WORLD_MARK.BLOOD,
    weightActive: 70,
    weightPassive: 40,
    weightSocial: 75,
  },
  {
    name: 'Diplomat',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.EXTRA,
    secondaryAxis: AXIS_TAG.OTHERS,
    motivation: MOTIVATION_TAG.BELONGING,
    worldMark: WORLD_MARK.BREATH,
    weightActive: 30,
    weightPassive: 45,
    weightSocial: 85,
  },
  {
    name: 'Merchant',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.EXTRA,
    secondaryAxis: AXIS_TAG.CAUTIOUS,
    motivation: MOTIVATION_TAG.WEALTH,
    worldMark: WORLD_MARK.BREATH,
    weightActive: 40,
    weightPassive: 35,
    weightSocial: 80,
  },
  {
    name: 'Preacher',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.EXTRA,
    secondaryAxis: AXIS_TAG.OTHERS,
    motivation: MOTIVATION_TAG.RECOGNITION,
    worldMark: WORLD_MARK.TEAR,
    weightActive: 35,
    weightPassive: 50,
    weightSocial: 80,
  },

  // ── Seekers (8-11): Knowledge + Cautious ──────────────
  {
    name: 'Scholar',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CAUTIOUS,
    secondaryAxis: AXIS_TAG.INTRO,
    motivation: MOTIVATION_TAG.KNOWLEDGE,
    worldMark: WORLD_MARK.EYE,
    weightActive: 25,
    weightPassive: 80,
    weightSocial: 45,
  },
  {
    name: 'Investigator',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.CAUTIOUS,
    secondaryAxis: AXIS_TAG.INTRO,
    motivation: MOTIVATION_TAG.KNOWLEDGE,
    worldMark: WORLD_MARK.EYE,
    weightActive: 55,
    weightPassive: 65,
    weightSocial: 40,
  },
  {
    name: 'Sage',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CAUTIOUS,
    secondaryAxis: AXIS_TAG.STABLE,
    motivation: MOTIVATION_TAG.MASTERY,
    worldMark: WORLD_MARK.TEAR,
    weightActive: 20,
    weightPassive: 85,
    weightSocial: 50,
  },
  {
    name: 'Archivist',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CAUTIOUS,
    secondaryAxis: AXIS_TAG.ORDER,
    motivation: MOTIVATION_TAG.KNOWLEDGE,
    worldMark: WORLD_MARK.EAR,
    weightActive: 15,
    weightPassive: 90,
    weightSocial: 35,
  },

  // ── Creators (12-15): Creation + Stable ───────────────
  {
    name: 'Artisan',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.STABLE,
    secondaryAxis: AXIS_TAG.SELF,
    motivation: MOTIVATION_TAG.CREATION,
    worldMark: WORLD_MARK.SKIN,
    weightActive: 50,
    weightPassive: 65,
    weightSocial: 45,
  },
  {
    name: 'Builder',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.STABLE,
    secondaryAxis: AXIS_TAG.ORDER,
    motivation: MOTIVATION_TAG.CREATION,
    worldMark: WORLD_MARK.BONE,
    weightActive: 65,
    weightPassive: 55,
    weightSocial: 40,
  },
  {
    name: 'Healer',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.STABLE,
    secondaryAxis: AXIS_TAG.OTHERS,
    motivation: MOTIVATION_TAG.PROTECTION,
    worldMark: WORLD_MARK.TEAR,
    weightActive: 30,
    weightPassive: 70,
    weightSocial: 65,
  },
  {
    name: 'Cultivator',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.STABLE,
    secondaryAxis: AXIS_TAG.CAUTIOUS,
    motivation: MOTIVATION_TAG.CREATION,
    worldMark: WORLD_MARK.SKIN,
    weightActive: 45,
    weightPassive: 70,
    weightSocial: 50,
  },

  // ── Adventurers (16-19): Freedom + Bold ───────────────
  {
    name: 'Explorer',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.BOLD,
    secondaryAxis: AXIS_TAG.EXTRA,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.EYE,
    weightActive: 85,
    weightPassive: 30,
    weightSocial: 40,
  },
  {
    name: 'Pioneer',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.BOLD,
    secondaryAxis: AXIS_TAG.ORDER,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.BREATH,
    weightActive: 80,
    weightPassive: 25,
    weightSocial: 50,
  },
  {
    name: 'Nomad',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.BOLD,
    secondaryAxis: AXIS_TAG.INTRO,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.EAR,
    weightActive: 75,
    weightPassive: 35,
    weightSocial: 35,
  },
  {
    name: 'Wanderer',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.BOLD,
    secondaryAxis: AXIS_TAG.REACTIVE,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.BREATH,
    weightActive: 70,
    weightPassive: 40,
    weightSocial: 30,
  },

  // ── Warriors (20-23): Combat + Reactive ───────────────
  {
    name: 'Berserker',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.REACTIVE,
    secondaryAxis: AXIS_TAG.BOLD,
    motivation: MOTIVATION_TAG.SURVIVAL,
    worldMark: WORLD_MARK.BLOOD,
    weightActive: 95,
    weightPassive: 10,
    weightSocial: 20,
  },
  {
    name: 'Duelist',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.REACTIVE,
    secondaryAxis: AXIS_TAG.SELF,
    motivation: MOTIVATION_TAG.MASTERY,
    worldMark: WORLD_MARK.BLOOD,
    weightActive: 85,
    weightPassive: 25,
    weightSocial: 30,
  },
  {
    name: 'Hunter',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.REACTIVE,
    secondaryAxis: AXIS_TAG.CAUTIOUS,
    motivation: MOTIVATION_TAG.MASTERY,
    worldMark: WORLD_MARK.BLOOD,
    weightActive: 80,
    weightPassive: 40,
    weightSocial: 25,
  },
  {
    name: 'Veteran',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.REACTIVE,
    secondaryAxis: AXIS_TAG.STABLE,
    motivation: MOTIVATION_TAG.PROTECTION,
    worldMark: WORLD_MARK.BONE,
    weightActive: 70,
    weightPassive: 50,
    weightSocial: 45,
  },

  // ── Shadows (24-27): Stealth + Self ───────────────────
  {
    name: 'Assassin',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.SELF,
    secondaryAxis: AXIS_TAG.REACTIVE,
    motivation: MOTIVATION_TAG.POWER,
    worldMark: WORLD_MARK.SHADOW,
    weightActive: 80,
    weightPassive: 35,
    weightSocial: 20,
  },
  {
    name: 'Thief',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.SELF,
    secondaryAxis: AXIS_TAG.CAUTIOUS,
    motivation: MOTIVATION_TAG.WEALTH,
    worldMark: WORLD_MARK.SHADOW,
    weightActive: 70,
    weightPassive: 40,
    weightSocial: 35,
  },
  {
    name: 'Spy',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.SELF,
    secondaryAxis: AXIS_TAG.INTRO,
    motivation: MOTIVATION_TAG.KNOWLEDGE,
    worldMark: WORLD_MARK.SHADOW,
    weightActive: 55,
    weightPassive: 45,
    weightSocial: 65,
  },
  {
    name: 'Trickster',
    direction: DIRECTION_TAG.SOCIAL,
    primaryAxis: AXIS_TAG.SELF,
    secondaryAxis: AXIS_TAG.CHAOS,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.SHADOW,
    weightActive: 60,
    weightPassive: 30,
    weightSocial: 70,
  },

  // ── Outcasts (28-31): Chaos + Survival ────────────────
  {
    name: 'Survivor',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CHAOS,
    secondaryAxis: AXIS_TAG.REACTIVE,
    motivation: MOTIVATION_TAG.SURVIVAL,
    worldMark: WORLD_MARK.SKIN,
    weightActive: 65,
    weightPassive: 60,
    weightSocial: 25,
  },
  {
    name: 'Hermit',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CHAOS,
    secondaryAxis: AXIS_TAG.INTRO,
    motivation: MOTIVATION_TAG.SURVIVAL,
    worldMark: WORLD_MARK.EAR,
    weightActive: 30,
    weightPassive: 85,
    weightSocial: 15,
  },
  {
    name: 'Rebel',
    direction: DIRECTION_TAG.ACTIVE,
    primaryAxis: AXIS_TAG.CHAOS,
    secondaryAxis: AXIS_TAG.BOLD,
    motivation: MOTIVATION_TAG.FREEDOM,
    worldMark: WORLD_MARK.BLOOD,
    weightActive: 80,
    weightPassive: 20,
    weightSocial: 50,
  },
  {
    name: 'Outcast',
    direction: DIRECTION_TAG.PASSIVE,
    primaryAxis: AXIS_TAG.CHAOS,
    secondaryAxis: AXIS_TAG.SELF,
    motivation: MOTIVATION_TAG.SURVIVAL,
    worldMark: WORLD_MARK.SHADOW,
    weightActive: 55,
    weightPassive: 50,
    weightSocial: 20,
  },
] as const;

/**
 * Register all 32 default archetypes to storage.
 * @returns Number of registered archetypes
 */
export function initializeDefaultArchetypes(storage: ArchetypeStorage): number {
  let count = 0;
  for (const def of ARCHETYPE_DEFINITIONS) {
    registerArchetype(storage, def);
    count++;
  }
  return count;
}
